language: R
sudo: required
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx
  
osx_image: xcode10.2

env:
 global:
   - CRAN: http://cran.rstudio.com

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then Rscript -e 'covr::codecov()'; fi
  
  # For automatic deploy of the website
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
