name: fmcmc website

on: [push, pull_request]

env:
  cntr: rocker/tidyverse:latest

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${{ cntr }}

      - name: Building website
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt ${cntr} Rscript -e 'install.packages("pkgdown");pkgdown::build_site()'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

